# Generated by Django 5.0.4 on 2024-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myblog",
            name="views",
        ),
        migrations.AddField(
            model_name="myblog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, help_text="Количество просмотров", verbose_name="Просмотры"
            ),
        ),
    ]
