# Generated by Django 5.0.4 on 2024-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_myblog_views_myblog_views_counter"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myblog",
            name="publication_sign",
            field=models.BooleanField(default=False, verbose_name="Признак публикации"),
        ),
    ]
